exports.DB_NAME= process.env.DB_NAME;
exports.DB_HOST= process.env.DB_HOST;
exports.PORT = process.env.PORT;
exports.USERNAME= process.env.USERNAME;
exports.PASSWORD= process.env.PASSWORD;
exports.REGION= process.env.REGION;
exports.API_KEY= process.env.API_KEY;
exports.URL= process.env.URL;
exports.TRANSLATE_URL= process.env.TRANSLATE_URL;